name: Node.js CI

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

      # uses: actions/setup-node@v3
      # with:
      #   node-version: ${{ env.NODE_VERSION }}
      #   cache: 'npm'

    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install, build
      run: |
        yarn install
        CI=false yarn build

    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        token: ${{ secrets.GH_PAT }}
        branch: gh-pages
        folder: build  
